#!/bin/sh /etc/rc.common

START=51
USE_PROCD=1
UHTTPD_BIN="/usr/sbin/uhttpd"
WATCHER_BIN="/scorekeeper/watcher.lua"

start_redirector()
{
        procd_open_instance
        procd_set_param respawn
        procd_set_param stderr 1
        procd_set_param command "$UHTTPD_BIN" -f -h /scorekeeper -x / -I redirector.lua -p 0.0.0.0:80
        procd_close_instance
}

start_watcher()
{
        procd_open_instance
        procd_set_param respawn
        procd_set_param stderr 1
        procd_set_param command "$WATCHER_BIN"
        procd_close_instance
}

start_service() 
{
        start_redirector()
        start_watcher()
}

